### ISSUE TITLE
Add Crosswalk Attribute

### ISSUE THREAD

**Issue by metaweidner** [uhlibraries-digital/bcdams-map#66]
This will facilitate mapping to other metadata schema such as MODS for Avalon.

**Comment by seanlw** [comment]
Avalon MODS crosswalk https://github.com/uhlibraries-digital/bcdams-map/wiki/06-Avalon-Crosswalk

**Comment by metaweidner** [comment]
abe616ef9545949a9000bd98aa49e6235019e166
ecdf0195810b581d060be605228c08ab776f5b06
65858874702646674e3e4383133f309afc624ffb

**Comment by seanlw** [comment]
@amgaynor Since the addition of note types, can you map out the MAP fields with the appropriate Note Types.

https://github.com/uhlibraries-digital/bcdams-map/wiki/06-Avalon-Crosswalk

@metaweidner once this is done there will be more changes in the crosswalk attribute, I'll let you know what that might look like depending on what gets mapped.

**Comment by amgaynor** [comment]
@seanlw I've updated it with the notes that we had worked on before. Though I'm still interested to hear @metaweidner and others' thoughts our (ab)use of the `Note` field, bearing in mind that it's a bit of a stopgap measure.

**Comment by seanlw** [comment]
@metaweidner can you add in the crosswalk segments to `Collection`, `Preservation Location`, and `Donor`. Because these share the same field `Note`, add the attribute `type` to the `avalon` attribute. The `type` is defined in the crosswalk wiki page. Also, please add type `general` to uhlib.note field.

example:

```
crosswalk:
  avalon:
    label: note
    type: collection
```

**Comment by metaweidner** [comment]
@seanlw Will these mappings work for now, assuming that we can get the `Identifier` ingest to work? It seems like `Collection` is already captured in Avalon's `Collection` and `Unit` facets.

**Donor**
```
crosswalk:
    avalon:
        label: note
        type: donor
```

**Preservation Location**
```
crosswalk:
    avalon:
        label: identifier
        type: preservation location
```

**Identifier**
```
crosswalk:
    avalon:
        label: identifier
        type: other
```

**Comment by seanlw** [comment]
@metaweidner yeah, I think that will work

**Comment by metaweidner** [comment]
@seanlw I added `Collection` to the mix as well given the limitations of the MAP in identifying the `Collection` and `Unit` for Avalon ingest. https://github.com/uhlibraries-digital/bcdams-map/commit/de6b429e8b535cfdcfa176e5f88a65505377aab6

**Comment by seanlw** [comment]
@metaweidner I noticed that the avalon label for `Other Identifier` has been changed to `identifier`. It will need to remain `Other Identifier`. I know the `Identifier Type` is giving us trouble but I do know it will fail if `Other Identifier` is not there.

**Comment by metaweidner** [comment]
@seanlw 7dd0541a3e47054bab050ff57f2d39358cc55e29

**Comment by seanlw** [comment]
@metaweidner some changes are needed to the avalon crosswalk

- `Preservation Location` needs a label change to `Other Identifier`
- uhlib.note needs a note type of `general`

**Comment by metaweidner** [comment]
@seanlw aa3a77e

**Comment by amgaynor** [comment]
@metaweidner @seanlw I've updated the [Avalon Crosswalk wiki page](https://github.com/uhlibraries-digital/bcdams-map/wiki/06-Avalon-Crosswalk) to include the ASpace URI mapping.

We'll need the avalon crosswalk added to the MAP for the Brays export.

I think:

**ASpace URI**
```
crosswalk:
    avalon:
        label: "other identifier"
        type: "aspace uri"
```
